In [3]:
import numpy as np 
import pandas as pd

In [4]:
truedata=pd.read_csv("True.csv")

In [5]:
fakedata=pd.read_csv("Fake.csv")

In [6]:
truedata['result']=1
fakedata['result']=0

In [7]:
truedata.shape

(21417, 5)

In [8]:
fakedata.shape

(23481, 5)

In [9]:
data=pd.concat([truedata,fakedata],axis=0)

In [10]:
data.duplicated().sum()

209

In [11]:
data.drop_duplicates(inplace=True)

In [12]:
data.drop(['title','subject','date'],axis=1,inplace=True)

In [13]:
data=data.sample(frac=1).reset_index()

In [14]:
data.shape

(44689, 3)

In [15]:
import re
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
corpus = []
for i in range(0,44689):
  review = re.sub('[^a-zA-Z]', ' ', data['text'][i])
  review = review.lower()
  review = review.split()
  ps = PorterStemmer()
  all_stopwords = stopwords.words('english')
  all_stopwords.remove('not')
  review = [ps.stem(word) for word in review if not word in set(all_stopwords)]
  review = ' '.join(review)
  corpus.append(review)

[nltk_data] Downloading package stopwords to C:\Users\Sahana
[nltk_data]     K\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [16]:
data.iloc[0, data.columns.get_loc("text")]

'What s a million dollars between friends? To hell with human rights violations Hillary s got a campaign to win!A major Clinton Foundation donor regularly arrests dissidents and brutally tortures them to extract confessions, according to a new report from Amnesty International.The New York Times reports that despite promises of reform, the Moroccan government continues to use  violent interrogation tactics  to  crush dissent. Moroccan King Mohammed VI recently hosted Bill and Chelsea Clinton at a Clinton Global Initiative conference in Marrakech, where guests were  chauffeured across the city to an opulent 56-room palace that boasts a private collection of Arabian horses, overlooks the snow-capped Atlas Mountains and serves a fine-dining menu of  biolight  cuisine,  according to the Washington Post.    During the conference Bill cited  Morocco s longstanding friendship to my family,  and thanked the king, who pledged as much as $500,000 toward the construction of the Clinton Library, a

In [17]:
print(corpus[0])

million dollar friend hell human right violat hillari got campaign win major clinton foundat donor regularli arrest dissid brutal tortur extract confess accord new report amnesti intern new york time report despit promis reform moroccan govern continu use violent interrog tactic crush dissent moroccan king moham vi recent host bill chelsea clinton clinton global initi confer marrakech guest chauffeur across citi opul room palac boast privat collect arabian hors overlook snow cap atla mountain serv fine dine menu biolight cuisin accord washington post confer bill cite morocco longstand friendship famili thank king pledg much toward construct clinton librari well ocp corpor govern own phosphat mine compani donat least million clinton foundat interview politico former ocp miner describ wit verbal physic abus dole govern member minor advoc independ western sahara amnesti intern secretari gener salil shetti blast moroccan govern statement say morocco leader portray imag liber human right fr

In [18]:
data['text']=corpus

In [19]:
data.iloc[0, data.columns.get_loc("text")]

'million dollar friend hell human right violat hillari got campaign win major clinton foundat donor regularli arrest dissid brutal tortur extract confess accord new report amnesti intern new york time report despit promis reform moroccan govern continu use violent interrog tactic crush dissent moroccan king moham vi recent host bill chelsea clinton clinton global initi confer marrakech guest chauffeur across citi opul room palac boast privat collect arabian hors overlook snow cap atla mountain serv fine dine menu biolight cuisin accord washington post confer bill cite morocco longstand friendship famili thank king pledg much toward construct clinton librari well ocp corpor govern own phosphat mine compani donat least million clinton foundat interview politico former ocp miner describ wit verbal physic abus dole govern member minor advoc independ western sahara amnesti intern secretari gener salil shetti blast moroccan govern statement say morocco leader portray imag liber human right f

In [20]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44689 entries, 0 to 44688
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   index   44689 non-null  int64 
 1   text    44689 non-null  object
 2   result  44689 non-null  int64 
dtypes: int64(2), object(1)
memory usage: 1.0+ MB


In [21]:
data['result']

0        0
1        0
2        0
3        1
4        1
        ..
44684    0
44685    1
44686    0
44687    1
44688    0
Name: result, Length: 44689, dtype: int64

In [22]:
data.iloc[:,-1].values

array([0, 0, 0, ..., 0, 1, 0], dtype=int64)

In [24]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=15000)
x = cv.fit_transform(corpus).toarray()
y =data.iloc[:,-1].values

In [25]:
print(x[0])

[0 0 0 ... 0 0 0]


In [26]:
with np.printoptions(threshold=np.inf):
    print(x[0])

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 3 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 

In [27]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=0)

## Logistic regression

In [28]:
from sklearn.linear_model import LogisticRegression

lr=LogisticRegression(max_iter=200)
lr.fit(x_train,y_train)

LogisticRegression(max_iter=200)

In [29]:
y_pred=lr.predict(x_test)

In [30]:
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[1 1]
 [0 0]
 [0 0]
 ...
 [1 1]
 [0 0]
 [1 1]]


In [31]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[7033   40]
 [  36 6298]]


0.9943313194599835

In [32]:
y_pred1=lr.predict(x_train)

In [33]:
accuracy_score(y_train, y_pred1)

1.0

 # Decision tree classifier

In [34]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(x_train, y_train)


DecisionTreeClassifier(criterion='entropy', random_state=0)

In [35]:
y_pred = classifier.predict(x_test)

In [36]:
accuracy_score(y_test, y_pred)

0.9955993137913031

In [37]:
ypred1=classifier.predict(x_train)

accuracy_score(y_train,ypred1)

1.0

# Random forest classifier

In [38]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier.fit(x_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

In [39]:
y_pred = classifier.predict(x_test)

In [40]:
accuracy_score(y_test, y_pred)

0.9742671738643992

In [41]:
ypred1=classifier.predict(x_train)

accuracy_score(y_train,ypred1)

0.9992967201585576